import type { ChallengePath } from "./challenges";

export type ChallengeEmailTokenTarget = {
  path: ChallengePath;
  day: number;
};

export type ChallengeEmailCta = {
  label: string;
  tokenTarget: ChallengeEmailTokenTarget;
};

export type ChallengeEmailTemplate = {
  path: ChallengePath;
  day: number;
  title: string;
  subject: string;
  previewText: string;
  greeting: string;
  intro: readonly string[];
  previousChallengeCta?: ChallengeEmailCta;
  lesson: readonly string[];
  challenge: readonly string[];
  currentChallengeCta: ChallengeEmailCta;
  outro: readonly string[];
  signature: string;
};

export const challengeEmailTemplates = {
  stability: [
    {
      path: "stability",
      day: 0,
      title: "Day 0 — Your Foundation",
      subject: "Your Stability Journey Starts Today",
      previewText: "Your Financial Profile is ready.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Your Financial Profile is ready.",
        "One thing stood out immediately.",
        "Right now, your Financial Stability Coin has the most room for growth.",
        "This isn't bad news.",
        "It's actually the best place to start.",
        "Most people think financial progress begins with investing.",
        "Others think it begins with earning more money.",
        "In reality, it begins with stability.",
        "Because when your financial foundation feels shaky, every financial decision becomes harder.",
        "Saving becomes harder.",
        "Investing becomes harder.",
        "Planning becomes harder.",
        "Over the next 7 days, you'll receive one lesson and one challenge each day.",
        "These aren't theoretical exercises.",
        "They're small actions designed to help you build more control over your money.",
      ],
      lesson: [],
      challenge: [
        "Today's challenge:",
        "Open your virtual wallet simulator.",
        "Review your last 10 transactions.",
        "Don't judge yourself.",
        "Don't change anything.",
        "Simply observe.",
        "Ask yourself:",
        "\"Which of these purchases genuinely improved my life?\"",
      ],
      currentChallengeCta: {
        label: "Complete the challenge",
        tokenTarget: { path: "stability", day: 0 },
      },
      outro: ["Tomorrow we'll uncover one of the biggest causes of financial instability."],
      signature: "The FinLevels Team",
    },
    {
      path: "stability",
      day: 1,
      title: "Day 1 — Invisible Spending",
      subject: "Did you complete yesterday's challenge?",
      previewText: "Awareness is the first step toward control.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Yesterday you reviewed your recent transactions.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "stability", day: 0 },
      },
      lesson: [
        "Awareness is the first step toward control.",
        "Today's lesson:",
        "Financial instability rarely comes from one huge mistake.",
        "More often, it comes from dozens of small decisions that slowly drain your resources.",
        "A forgotten subscription.",
        "An impulse purchase.",
        "A recurring charge you've stopped noticing.",
        "Individually they seem harmless.",
        "Together they can quietly limit your progress.",
      ],
      challenge: [
        "Today's challenge:",
        "Find one recurring expense in your life.",
        "It could be:",
        "A subscription",
        "A membership",
        "A service",
        "An app",
        "Write it down.",
        "Don't cancel it.",
        "Just identify it.",
        "Tomorrow we'll explore why money decisions are often emotional rather than logical.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "stability", day: 1 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "stability",
      day: 2,
      title: "Day 2 — The Emotion Behind Spending",
      subject: "Money follows emotion more than logic",
      previewText: "Many purchases aren't driven by necessity. They're driven by emotion.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Before today's challenge:",
        "Did you identify a recurring expense yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "stability", day: 1 },
      },
      lesson: [
        "Now let's talk about something most people overlook.",
        "Many purchases aren't driven by necessity.",
        "They're driven by emotion.",
        "Stress.",
        "Boredom.",
        "Reward.",
        "Frustration.",
        "Excitement.",
        "The purchase feels financial.",
        "The trigger is emotional.",
        "The more aware you become of these triggers, the more control you gain.",
      ],
      challenge: [
        "Today's challenge:",
        "Think about the last purchase you regret.",
        "Ask yourself:",
        "\"What was I feeling before I made that purchase?\"",
        "Write down the answer.",
        "No judgment.",
        "Just awareness.",
        "Tomorrow you'll track every dollar for one day.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "stability", day: 2 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "stability",
      day: 3,
      title: "Day 3 — Awareness Creates Control",
      subject: "Most people have no idea where their money goes",
      previewText: "You can't improve what you don't see.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Yesterday you identified an emotional trigger.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "stability", day: 2 },
      },
      lesson: [
        "That's important.",
        "Because awareness changes behavior.",
        "Today's lesson:",
        "People often say:",
        "\"I don't know where my money goes.\"",
        "That's not a budgeting problem.",
        "It's an awareness problem.",
        "You can't improve what you don't see.",
      ],
      challenge: [
        "Today's challenge:",
        "Track every expense you make today.",
        "Every single one.",
        "Coffee.",
        "Lunch.",
        "Subscriptions.",
        "Transportation.",
        "Everything.",
        "Use your notes app if needed.",
        "The goal isn't perfection.",
        "The goal is visibility.",
        "Tomorrow we'll look at creating financial breathing room.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "stability", day: 3 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "stability",
      day: 4,
      title: "Day 4 — Create Margin",
      subject: "Financial stability starts with breathing room",
      previewText: "Financial stability grows when you create margin.",
      greeting: "Hi {{first_name}},",
      intro: [
        "How did yesterday's tracking exercise feel?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "stability", day: 3 },
      },
      lesson: [
        "Most people discover at least one surprise.",
        "Today's lesson:",
        "Financial stress grows when every dollar already has a destination.",
        "Financial stability grows when you create margin.",
        "Margin means having a little extra room between what comes in and what goes out.",
      ],
      challenge: [
        "Today's challenge:",
        "Identify one expense you can reduce, pause, or replace this week.",
        "Don't make a drastic change.",
        "Find one realistic adjustment.",
        "Small changes repeated consistently create meaningful results.",
        "Tomorrow we'll start building your financial buffer.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "stability", day: 4 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "stability",
      day: 5,
      title: "Day 5 — Your First Buffer",
      subject: "A small buffer can prevent a big crisis",
      previewText: "This is the beginning of your financial safety buffer.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Yesterday you identified one area where you could create more margin.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "stability", day: 4 },
      },
      lesson: [
        "That's progress.",
        "Today's lesson:",
        "Many financial emergencies aren't large.",
        "They're inconvenient.",
        "A car repair.",
        "An unexpected bill.",
        "A broken phone.",
        "The problem isn't the event.",
        "The problem is having no buffer.",
      ],
      challenge: [
        "Today's challenge:",
        "Set aside a small amount of money today.",
        "The amount doesn't matter.",
        "The habit does.",
        "Create a separate space for it.",
        "This is the beginning of your financial safety buffer.",
        "Tomorrow we'll talk about making good habits automatic.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "stability", day: 5 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "stability",
      day: 6,
      title: "Day 6 — Systems Beat Motivation",
      subject: "The secret isn't discipline",
      previewText: "Successful financial habits don't depend on motivation. They depend on systems.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Congratulations.",
        "You've completed six days of action.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "stability", day: 5 },
      },
      lesson: [
        "That's already more financial work than most people do in months.",
        "Today's lesson:",
        "Successful financial habits don't depend on motivation.",
        "They depend on systems.",
        "Motivation comes and goes.",
        "Systems keep working.",
        "That's why the most financially stable people automate as much as possible.",
      ],
      challenge: [
        "Today's challenge:",
        "Create one simple money rule.",
        "Examples:",
        "Save a percentage of every paycheck",
        "Review spending every Sunday",
        "Wait 24 hours before non-essential purchases",
        "Choose one rule you'll follow for the next month.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "stability", day: 6 },
      },
      outro: ["Welcome to the next level of your financial journey."],
      signature: "The FinLevels Team",
    },
  ],
  saving: [
    {
      path: "saving",
      day: 0,
      title: "Day 0 — Your Saving Identity",
      subject: "Your Saving Profile is now active",
      previewText: "Your Saving Coin is your weakest financial area right now.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Your Financial Profile is ready.",
        "One pattern is clear.",
        "Your Saving Coin is your weakest financial area right now.",
        "This doesn't mean you can't save.",
        "It means saving is not yet a consistent behavior in your financial system.",
        "And that changes everything.",
        "Because saving is not about income.",
        "It's about structure.",
        "Over the next 7 days, you'll build a simple saving system through small daily actions.",
        "Not theory.",
        "Not advice.",
        "Real behavior shifts.",
      ],
      lesson: [],
      challenge: [
        "Today's challenge:",
        "Look at your last month of income.",
        "Ask yourself one question:",
        "\"Did I pay myself first?\"",
        "No judgment.",
        "Just observation.",
      ],
      currentChallengeCta: {
        label: "Complete the challenge",
        tokenTarget: { path: "saving", day: 0 },
      },
      outro: ["Tomorrow we start building your first saving habit."],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 1,
      title: "Day 1 — Saving is Not What's Left",
      subject: "The biggest saving mistake",
      previewText: "Saving only becomes consistent when it is intentional.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Did you review your income from last month?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 0 },
      },
      lesson: [
        "Now let's correct one major misconception.",
        "Most people think saving happens after spending.",
        "In reality, that approach rarely works.",
        "Because spending always expands to fill what's available.",
        "Saving only becomes consistent when it is intentional.",
        "Not leftover.",
      ],
      challenge: [
        "Today's challenge:",
        "Define a simple saving rule for yourself:",
        "Example:",
        "\"I save 10% of all income first\"",
        "\"I save $X immediately after getting money\"",
        "Write your rule down.",
        "Do not apply it yet.",
        "Just define it.",
        "Tomorrow we turn it into action.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 1 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 2,
      title: "Day 2 — Your First Commitment",
      subject: "Your saving behavior starts today",
      previewText: "You are becoming someone who saves first.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Yesterday you defined your saving rule.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 1 },
      },
      lesson: [
        "Today we activate it.",
        "Most people fail at saving because they try to save \"what is left.\"",
        "There is never anything left.",
        "So we reverse the logic.",
      ],
      challenge: [
        "Today's challenge:",
        "Take your first intentional saving action.",
        "Even if it is small.",
        "Even symbolic.",
        "The goal is not the amount.",
        "The goal is identity.",
        "You are becoming someone who saves first.",
        "Tomorrow we look at emotional spending vs saving consistency.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 2 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 3,
      title: "Day 3 — The Spending Pull",
      subject: "Why saving feels hard",
      previewText: "Saving is delayed and invisible. That imbalance creates friction.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Let's talk about something real.",
        "Did you take your first saving action yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 2 },
      },
      lesson: [
        "Saving is not difficult because people don't understand it.",
        "It's difficult because spending is emotional and immediate.",
        "Saving is delayed and invisible.",
        "That imbalance creates friction.",
      ],
      challenge: [
        "Today's challenge:",
        "Identify one purchase you made recently that was emotional, not necessary.",
        "Ask:",
        "\"Would I still make this purchase if I had already saved first?\"",
        "Write the answer honestly.",
        "Tomorrow we introduce a system to reduce this friction.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 3 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 4,
      title: "Day 4 — Remove Friction from Saving",
      subject: "Make saving automatic, not emotional",
      previewText: "Saving should not depend on discipline. It should depend on design.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Yesterday you reflected on emotional spending.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 3 },
      },
      lesson: [
        "Now we shift behavior.",
        "Saving should not depend on discipline.",
        "It should depend on design.",
      ],
      challenge: [
        "Today's challenge:",
        "Create one friction barrier for spending OR one shortcut for saving.",
        "Examples:",
        "Move savings to a separate account",
        "Hide a spending app",
        "Rename your savings account \"Future Me\"",
        "Set a rule before non-essential purchases",
        "Small systems beat strong motivation.",
        "Tomorrow we start building consistency.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 4 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 5,
      title: "Day 5 — Consistency Over Intensity",
      subject: "Why most saving plans fail",
      previewText: "Commit to a repeating saving action.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Most people try to save intensely.",
        "Then stop completely.",
        "Then restart again.",
        "Did you set your friction system yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 4 },
      },
      lesson: ["That cycle prevents progress.", "We fix that today."],
      challenge: [
        "Today's challenge:",
        "Commit to a repeating saving action.",
        "Something simple:",
        "Weekly transfer",
        "Fixed percentage",
        "Fixed day saving habit",
        "It must be repeatable, not perfect.",
        "Tomorrow we automate it.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 5 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 6,
      title: "Day 6 — Automation is Wealth Behavior",
      subject: "The habit that builds wealth silently",
      previewText: "The most financially consistent people rely on automation.",
      greeting: "Hi {{first_name}},",
      intro: [
        "You've built awareness.",
        "Did you commit to your repeating saving action yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 5 },
      },
      lesson: [
        "Now we build stability.",
        "The most financially consistent people don't rely on memory.",
        "They rely on automation.",
      ],
      challenge: [
        "Today's challenge:",
        "Set up or simulate an automatic saving behavior.",
        "Even if manual.",
        "Even if small.",
        "The key is repetition without thinking.",
        "This is how saving becomes identity, not effort.",
        "Tomorrow we close your 7-day saving system.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 6 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "saving",
      day: 7,
      title: "Day 7 — Your Saving System",
      subject: "You now have a saving system",
      previewText: "This is no longer theory. It is a system.",
      greeting: "Hi {{first_name}},",
      intro: [
        "You've completed 7 days.",
        "Most people never reach this point.",
        "Did you set up your automatic saving behavior?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "saving", day: 6 },
      },
      lesson: [
        "Let's summarize what you built:",
        "Awareness of spending behavior",
        "A personal saving rule",
        "A first saving action",
        "Emotional spending awareness",
        "A friction system",
        "A consistency habit",
        "A simple automation mindset",
        "This is no longer theory.",
        "It is a system.",
      ],
      challenge: [
        "Today's challenge:",
        "Write one sentence:",
        "\"What kind of saver am I becoming?\"",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "saving", day: 7 },
      },
      outro: ["This is your identity shift."],
      signature: "The FinLevels Team",
    },
  ],
  investing: [
    {
      path: "investing",
      day: 0,
      title: "Day 0 — Your Investment Gap",
      subject: "Your investing profile is ready",
      previewText: "Your Investing Coin is currently your weakest area.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Your Financial Profile is ready.",
        "One insight stands out.",
        "Your Investing Coin is currently your weakest area.",
        "This doesn't mean you are \"bad with investing.\"",
        "It means investing is not yet part of your financial behavior system.",
        "And that can change.",
        "Over the next 7 days, you will build a foundation for thinking like an investor.",
        "Not trading.",
        "Not speculation.",
        "Behavior.",
      ],
      lesson: [],
      challenge: [
        "Today's challenge:",
        "Write down your answer to this question:",
        "\"What does investing mean to me today?\"",
        "Be honest.",
        "No research.",
        "No pressure.",
      ],
      currentChallengeCta: {
        label: "Complete the challenge",
        tokenTarget: { path: "investing", day: 0 },
      },
      outro: ["Tomorrow we reshape that definition."],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 1,
      title: "Day 1 — Investing is Not Gambling",
      subject: "Your investing mindset starts here",
      previewText: "Investing is ownership over time.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Did you define what investing means to you?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 0 },
      },
      lesson: [
        "Now let's correct a common misunderstanding.",
        "Investing is not gambling.",
        "Investing is ownership over time.",
        "It is not about predicting.",
        "It is about participating in growth.",
      ],
      challenge: [
        "Today's challenge:",
        "Write 3 differences between:",
        "Investing",
        "Gambling",
        "Use your own words.",
        "Tomorrow we talk about time — your most powerful investing tool.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 1 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 2,
      title: "Day 2 — Time is Your Real Advantage",
      subject: "Time is your strongest investing asset",
      previewText: "Time + consistency is your biggest investing advantage.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Yesterday you separated investing from gambling.",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 1 },
      },
      lesson: [
        "Now let's introduce your biggest advantage.",
        "Time.",
        "Most people think investing is about money.",
        "It is actually about time + consistency.",
      ],
      challenge: [
        "Today's challenge:",
        "Calculate how many years you have until age 60.",
        "Write that number down.",
        "That number is your real investing power.",
        "Tomorrow we explore how companies actually create value.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 2 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 3,
      title: "Day 3 — What You Actually Invest In",
      subject: "You already understand investing more than you think",
      previewText: "Investing starts with understanding value.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Most people think investing starts with stocks.",
        "Did you calculate your years until 60 yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 2 },
      },
      lesson: [
        "But investing starts earlier.",
        "It starts with understanding value.",
      ],
      challenge: [
        "Today's challenge:",
        "Pick one company you know.",
        "Ask:",
        "\"How does this company make money?\"",
        "Write a simple explanation.",
        "Tomorrow we talk about index thinking.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 3 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 4,
      title: "Day 4 — You Don't Need to Predict",
      subject: "Stop trying to time the market",
      previewText: "Long-term investing is not prediction. It's participation.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Let's remove pressure.",
        "Did you explore how a company creates value yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 3 },
      },
      lesson: [
        "Most beginners believe they must predict the market.",
        "That's false.",
        "Long-term investing is not prediction.",
        "It's participation.",
      ],
      challenge: [
        "Today's challenge:",
        "Search or reflect on one index fund (or diversified fund concept).",
        "Do not invest.",
        "Just understand.",
        "Tomorrow we talk about risk.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 4 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 5,
      title: "Day 5 — Risk Comes From Ignorance",
      subject: "The real risk in investing",
      previewText: "Risk is not the market. Risk is lack of understanding.",
      greeting: "Hi {{first_name}},",
      intro: [
        "Most people fear investing because they think it is risky.",
        "Did you explore an index fund concept yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 4 },
      },
      lesson: [
        "But risk is not the market.",
        "Risk is lack of understanding.",
      ],
      challenge: [
        "Today's challenge:",
        "Write down one investing concept you do NOT understand yet.",
        "Example:",
        "ETFs",
        "Compound interest",
        "Diversification",
        "Tomorrow we explore long-term thinking.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 5 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 6,
      title: "Day 6 — Think in Decades",
      subject: "Investors think differently",
      previewText: "Short-term thinking creates fear. Long-term thinking creates patience.",
      greeting: "Hi {{first_name}},",
      intro: [
        "You've learned a lot in 6 days.",
        "Did you identify a concept you want to understand better yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 5 },
      },
      lesson: [
        "Now we shift mindset.",
        "Short-term thinking creates fear.",
        "Long-term thinking creates patience.",
      ],
      challenge: [
        "Today's challenge:",
        "Write a short message to your future self 10 years from now.",
        "Describe:",
        "Your financial life",
        "Your habits",
        "Your mindset",
        "Tomorrow we finalize your investing foundation.",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 6 },
      },
      outro: [],
      signature: "The FinLevels Team",
    },
    {
      path: "investing",
      day: 7,
      title: "Day 7 — Your Investor Identity",
      subject: "You are now thinking like an investor",
      previewText: "This is not financial education anymore. It is identity formation.",
      greeting: "Hi {{first_name}},",
      intro: [
        "You completed 7 days.",
        "Did you write your message to your future self yesterday?",
        "If you completed it, take a moment to celebrate.",
        "If not:",
      ],
      previousChallengeCta: {
        label: "Complete the previous challenge",
        tokenTarget: { path: "investing", day: 6 },
      },
      lesson: [
        "Let's reflect:",
        "You redefined investing",
        "You understood time advantage",
        "You learned ownership thinking",
        "You studied value creation",
        "You explored index behavior",
        "You identified risk knowledge gaps",
        "You imagined your future investor self",
        "This is not financial education anymore.",
        "It is identity formation.",
      ],
      challenge: [
        "Final challenge:",
        "Finish this sentence:",
        "\"I am becoming an investor who…\"",
      ],
      currentChallengeCta: {
        label: "Complete today's Challenge",
        tokenTarget: { path: "investing", day: 7 },
      },
      outro: ["This is your shift."],
      signature: "The FinLevels Team",
    },
  ],
} as const satisfies Record<ChallengePath, readonly ChallengeEmailTemplate[]>;

export function getChallengeEmailTemplate(
  path: ChallengePath,
  day: number,
): ChallengeEmailTemplate | null {
  return (
    challengeEmailTemplates[path].find((template) => template.day === day) ??
    null
  );
}
